kind: PersistentVolume
apiVersion: v1
metadata:
  name: org1peer0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/org1peer0"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: org1peer0-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
