kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume1
spec:
  storageClassName: hostpath
  capacity:
    storage: 100M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/vol1/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: volume1
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M