apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-cli
  labels:
    app: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
      - name: cli
        image: hyperledger/fabric-tools:1.2.1
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        volumeMounts:
        - name: orderer
          mountPath: "/orderer"
      initContainers:
      - name: install
        image: hyperledger/fabric-tools:1.2.1
        command: ["/bin/bash", "-c"]
        args:
         - git clone https://github.com/sbalashevich/benchmark && cd benchmark && ./jumpboxinit.sh
        volumeMounts:
        - name: orderer
          mountPath: "/orderer"
        - name: org1peer1
          mountPath: "/org1peer1"
        - name: org1peer2
          mountPath: "/org1peer2"
        - name: org2peer1
          mountPath: "/org2peer1"
        - name: org2peer2
          mountPath: "/org2peer2"
      volumes:
      - name: orderer
        emptyDir: {}
      - name: org1peer1
        emptyDir: {}
      - name: org1peer2
        emptyDir: {}
      - name: org2peer1
        emptyDir: {}
      - name: org2peer2
        emptyDir: {}
