apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
  labels:
    app: orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      containers:
      - name: orderer
        image: hyperledger/fabric-orderer
        command: ["orderer"]
#        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: "INFO"
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: "0.0.0.0"
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: "file"
        - name: ORDERER_GENERAL_GENESISFILE
          value: "/orderer/channel-artifacts/genesis.block"
        - name: ORDERER_GENERAL_LOCALMSPID
          value: "OrdererMSP"
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: "/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/msp/"
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: "/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: "/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
        volumeMounts:
        - name: orderer
          mountPath: "/orderer"
      volumes:
      - name: orderer
        persistentVolumeClaim:
          claimName: orderer-claim
---
kind: Service
apiVersion: v1
metadata:
  name: orderer
spec:
  selector:
    app: orderer
  ports:
  - protocol: TCP
    port: 7050
    targetPort: 7050