apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0
  namespace: org1
  labels:
    app: peer0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer0
  template:
    metadata:
      labels:
        app: peer0
    spec:
      containers:
      - name: peer0
        image: hyperledger/fabric-peer
        command: ["peer"]
        args: ["node", "start"]
#        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        env:
        - name: CORE_PEER_ID
          value: "peer0.org1.svc.cluster.local"
        - name: CORE_PEER_ADDRESS
          value: "peer0.org1.svc.cluster.local:7051"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: ""
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: "peer0.org1.svc.cluster.local:7051"
        - name: CORE_PEER_LOCALMSPID
          value: "Org1MSP"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "false"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/etc/hyperledger/fabric/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/etc/hyperledger/fabric/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/etc/hyperledger/fabric/tls/ca.crt"
        - name: FABRIC_CFG_PATH
          value: "/etc/hyperledger/fabric/"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "0.0.0.0:5984"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: ""
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: ""
        volumeMounts:
        - name: crypto
          mountPath: "/etc/hyperledger/fabric/"
      - name: couchdb
        image: hyperledger/fabric-couchdb
        env:
        - name: COUCHDB_USER
          value: ""
        - name: COUCHDB_PASSWORD
          value: ""
      volumes:
      - name: crypto
        persistentVolumeClaim:
          claimName: org1peer0-claim
---
kind: Service
apiVersion: v1
metadata:
  name: peer0
  namespace: org1
spec:
  selector:
    app: peer0
  ports:
  - protocol: TCP
    name: p1
    port: 7051
    targetPort: 7051
  - protocol: TCP
    name: p2
    port: 7053
    targetPort: 7053
  - protocol: TCP
    name: p3
    port: 7052
    targetPort: 7052
